# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smile.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'smile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsmile.proto\x12\x05smile\"D\n\x18TempoSampleUpdateMessage\x12(\n\x0ctempoSamples\x18\x01 \x03(\x0b\x32\x12.smile.TempoSample\"\xf8\x01\n\x0bTempoSample\x12\x11\n\tprimaryId\x18\x01 \x01(\t\x12\x15\n\rcmoSampleName\x18\x02 \x01(\t\x12\x13\n\x0b\x64mpSampleId\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssLevel\x18\x04 \x01(\t\x12\x1c\n\x14\x63ustodianInformation\x18\x05 \x01(\t\x12\x0f\n\x07\x62\x61itSet\x18\x06 \x01(\t\x12\x11\n\tgenePanel\x18\x07 \x01(\t\x12\x14\n\x0concotreeCode\x18\x08 \x01(\t\x12\x14\n\x0c\x63moPatientId\x18\t \x01(\t\x12\x14\n\x0c\x64mpPatientId\x18\n \x01(\t\x12\x11\n\trecapture\x18\x0b \x01(\t\"\xa3\x01\n\x11TempoCohortUpdate\x12\x10\n\x08\x63ohortId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x65ndUsers\x18\x04 \x03(\t\x12\x0f\n\x07pmUsers\x18\x05 \x03(\t\x12\x14\n\x0cprojectTitle\x18\x06 \x01(\t\x12\x17\n\x0fprojectSubtitle\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\tB]\n!org.mskcc.smile.commons.generatedZ8github.mskcc.org/cdsi/cdsi-protobuf/smile/smile_types_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!org.mskcc.smile.commons.generatedZ8github.mskcc.org/cdsi/cdsi-protobuf/smile/smile_types_v1'
  _globals['_TEMPOSAMPLEUPDATEMESSAGE']._serialized_start=22
  _globals['_TEMPOSAMPLEUPDATEMESSAGE']._serialized_end=90
  _globals['_TEMPOSAMPLE']._serialized_start=93
  _globals['_TEMPOSAMPLE']._serialized_end=341
  _globals['_TEMPOCOHORTUPDATE']._serialized_start=344
  _globals['_TEMPOCOHORTUPDATE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
